### ISSUE TITLE
rubygems-proxy.torquebox.org is down again

### ISSUE THREAD

**Issue by musdechocolate** [jruby/jruby-maven-plugins#131]
Hello,
rubygems-proxy.torquebox.org is redirecting to some strange website, and we are not able to retrieve the artifacts, could you please take a look? thanks a lot guys

**Comment by headius** [comment]
@musdechocolate The proxy servers are no longer used, and no longer the best way to resolve gem dependencies.

You should switch to using the mavengem extension, which does what the proxy servers did but entirely on your local machine.

https://github.com/jruby/mavengem/tree/master/mavengem-wagon

Let me know if you have any issues migrating!
